FROM python:3.12-slim

# Instalar herramientas básicas y actualizar el sistema
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    curl \
    git \
    vim \
    net-tools \
    build-essential

# Instalar Google Cloud SDK
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
    apt-get update && \
    apt-get install -y google-cloud-cli

WORKDIR /ws/code

ENV PYTHONPATH=/ws/code/src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .