FROM python:3.12-slim

ENV PYTHONUNBUFFERED=True

WORKDIR /usr/src/app

# Copiar solo los archivos necesarios
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
COPY ./src ./src

EXPOSE 8080

ENTRYPOINT ["streamlit", "run", "src/modelo_ml_streamlit.py", "--server.port=8080", "--server.address=0.0.0.0"]
